import { Colors, FontFamily } from '../../../Theme';
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flexDirection: 'row',
    borderColor: Colors.black,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.gray,
    paddingHorizontal: 11,
    backgroundColor: Colors.white,
    paddingTop: 12,
    paddingBottom: 7,
    alignContent: 'center',
    justifyContent: 'center',
  },
  passContainer: {
    paddingBottom: 7,
    flexDirection: 'row',
    borderColor: Colors.black,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.gray,
    paddingHorizontal: 11,
    backgroundColor: Colors.white,
    paddingTop: 12,
    alignContent: 'center',
    justifyContent: 'center',
  },
  outlinedInput: {
    flexDirection: 'row',
    borderColor: Colors.lightGray,
    backgroundColor: 'transparent',
    alignContent: 'center',
    justifyContent: 'center',
    borderRadius: 12,
  },
  bobInputContainer: {
    borderWidth: 1,
    borderTopRightRadius: 12,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    paddingTop: 0,
    height: 48,
    borderColor: Colors.lightGray,
    backgroundColor: 'transparent',
  },
  labelStyles: {
    fontFamily: FontFamily.base,
    color: '#000000',
  },
  underlineColor: {
    color: Colors.gray,
  },
  underlineBar: {
    height: 0,
  },
  leftIcon: {
    fontSize: 18,
    marginRight: 15,
    marginTop: 10,
  },
  flag: {
    width: 30,
    height: 25,
    borderColor: '#000000',
    borderWidth: 1,
  },
  error: {
    fontSize: 12,
    fontFamily: FontFamily.base,
    color: Colors.error,
    marginTop: 3,
  },
  errorMessage: {
    fontSize: 10,
    fontFamily: FontFamily.base,
    color: Colors.warn,
    marginTop: 3,
  },
  successMessage: {
    fontSize: 10,
    fontFamily: FontFamily.base,
    color: Colors.green,
    marginTop: 3,
  },
  errorContainer: {
    flexDirection: 'row',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.error,
    paddingHorizontal: 10,
    backgroundColor: Colors.white,
    paddingTop: 10,
    paddingBottom: 10,
    alignContent: 'center',
    justifyContent: 'center',
  },
  passedContainer: {
    flexDirection: 'row',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.secondary,
    paddingHorizontal: 10,
    backgroundColor: Colors.white,
    paddingTop: 10,
    paddingBottom: 10,
    alignContent: 'center',
    justifyContent: 'center',
  },
  textarea: { height: 150, textAlignVertical: 'top', color: 'black' },
  customFlag: {
    flexDirection: 'row',
    backgroundColor: 'white',
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingVertical: 13.5,
    marginVertical: 4,
    borderBottomColor: Colors.gray,
  },
  customPhoneFlag: {
    flexDirection: 'row',
    marginRight: 8,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 18,
    height: 48,
    alignItems: 'center',
    borderColor: Colors.lightGray,
  },
  dialCode: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  customFlagText: {
    fontFamily: FontFamily.bold,
    fontSize: 15,
    paddingHorizontal: 8,
    textAlign: 'center',
    color: Colors.darkGrey,
  },
  rightIcon: {
    marginTop: 8,
  },
  rightIconPhone: {
    position: 'absolute',
    right: 20,
    top: 20,
    zIndex: 99999,
  },
  rightIconInput: {
    position: 'absolute',
    right: 10,
    top: 18,
    zIndex: 99999,
  },
  phoneNumberBorderError: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.error,
  },
  phoneNumberBorderPassed: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: Colors.secondary,
  },
  customFlagTouched: {
    flexDirection: 'row',
    backgroundColor: 'white',
    paddingVertical: 13.5,
    borderBottomColor: Colors.gray,
  },
});
